# Obviously go ham on customising these

CHALLENGES = [
	"as much red as possible",
	"a sport item midair",
	"a bird",
	"an out of state licence plate",
	"of another team taking a photo",
	"a Disney scene reenactment",
	"your team's reflection",
	"a human pyramid",
	"with another team",
	"of your team in the tightest spot",
	"5 piggy backs",
	"your team camoflauged",
	"yoga poses",
	"everyone mid air (no jumping)",
	"someone 'holding' the rest of their team (using perspective)",
	"a found receipt",
	"2 (youth group) siblings",
	"a nativity scene in a bandstand",
	"everyone doing an impression of their leader",
	"an ATM",
	"a barber pole 💈",
	"a bridge",
	"a dog",
	"your team's shadow in the shape of an animal",
	"someone in a shopping trolley",
	"your team stopping in a no stopping zone",
	"a wedding dress",
	"a milkcrate",
	"your team crammed into a Telstra phone booth",
	"your team mimicking a statue",
	"someone trampolining",
	"someone swinging on a swing",
	"midair water",
	"a speedbump 4 stories underground",
	"a store that sells Seaweed Peptide Eye Gel",
	"a place that does Trivia Tuesdays",
	"a hairdresser that a team member has gone to in the last 3 months",
	"the third youngest team member's favourite restaurant",
	"a store sign that is all capital letters",
	"someone copying a 'slippery when wet' sign in front of the sign",
	"everyone on a tree off the ground",
	"a non english sign",
	"graphitti (found, not created 👀)",
	"a plaque with more than 27 words",
	"somewhere you could take a date",
	"somewhere you could donate clothes",
	"each teammate as a farm animal that's bigger than a fridge",
	"two people going down an up escalator and two people going up a down escalator giving two sets of handshakes with a person on the other escalator",
	"two people not not not not not not not not not not not not not not not not not not not touching pinky fingers",
	"your team recreating the \"One Direction Made in the AM\" album cover",
	"someone mid trust fall next to someone doing the Michael Jackson lean"
]
